In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

In [2]:
df = pd.read_csv('v3_master_combined.csv')

In [3]:
df

,postcode,Day_of_Week,Date,Branch Name,Total Sale,outercode,population,households,avg_household_income,unemployment_rate,...,is_covid_lockdown,Inferred_Brand,Days_Since_Open,rateable_value,distance_to_nearest_station_mi,distance_to_mcdonalds_kfc_mi,distance_to_mosque_mi,distance_to_university_mi,workplace_to_resident_ratio,ethnic_diversity_index
0,KA21 5DT,Saturday,2/1/2025,galos peri peri hamilton,347.53,KA21,686,548,13716.9812,0.430,...,0,Galos,0,1365.0,0.241441,2.277612,19.979787,14.023843,120.827,0.0160
1,KA21 5DT,Sunday,2/2/2025,galos peri peri hamilton,119.68,KA21,686,548,13716.9812,0.430,...,0,Galos,1,1365.0,0.241441,2.277612,19.979787,14.023843,120.827,0.0160
2,KA21 5DT,Monday,2/3/2025,galos peri peri hamilton,136.20,KA21,686,548,13716.9812,0.430,...,0,Galos,2,1365.0,0.241441,2.277612,19.979787,14.023843,120.827,0.0160
3,KA21 5DT,Tuesday,2/4/2025,galos peri peri hamilton,92.67,KA21,686,548,13716.9812,0.430,...,0,Galos,3,1365.0,0.241441,2.277612,19.979787,14.023843,120.827,0.0160
4,KA21 5DT,Wednesday,2/5/2025,galos peri peri hamilton,124.94,KA21,686,548,13716.9812,0.430,...,0,Galos,4,1365.0,0.241441,2.277612,19.979787,14.023843,120.827,0.0160
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69348,WV1 1TQ,Thursday,6/26/2025,rio's piri piri wolverhampton,794.19,WV1,345,168,36481.0000,0.086,...,0,Rio's,832,8354.0,0.201000,0.052655,0.729161,0.172899,0.915,0.6348
69349,WV1 1TQ,Friday,6/27/2025,rio's piri piri wolverhampton,582.61,WV1,345,168,36481.0000,0.086,...,0,Rio's,833,8354.0,0.201000,0.052655,0.729161,0.172899,0.915,0.6348
69350,WV1 1TQ,Saturday,6/28/2025,rio's piri piri wolverhampton,458.56,WV1,345,168,36481.0000,0.086,...,0,Rio's,834,8354.0,0.201000,0.052655,0.729161,0.172899,0.915,0.6348
69351,WV1 1TQ,Sunday,6/29/2025,rio's piri piri wolverhampton,174.68,WV1,345,168,36481.0000,0.086,...,0,Rio's,835,8354.0,0.201000,0.052655,0.729161,0.172899,0.915,0.6348
69352,WV1 1TQ,Monday,6/30/2025,rio's piri piri wolverhampton,380.27,WV1,345,168,36481.0000,0.086,...,0,Rio's,836,8354.0,0.201000,0.052655,0.729161,0.172899,0.915,0.6348

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 69353 entries, 0 to 69352
Data columns (total 48 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   postcode                        69353 non-null  object
 1   Day_of_Week                     69353 non-null  object
 2   Date                            69353 non-null  object
 3   Branch Name                     69353 non-null  object
 4   Total Sale                      67699 non-null  float64
 5   outercode                       69353 non-null  object
 6   population                      69353 non-null  int64
 7   households                      69353 non-null  int64
 8   avg_household_income            69353 non-null  float64
 9   unemployment_rate               69353 non-null  float64
 10  working                         69353 non-null  float64
 11  unemployed                      69353 non-null  float64
 12  ab                              69353 non-null  float64
 13  c1/c2                           69353 non-null  float64
 14  de                              69353 non-null  float64
 15  white                           69353 non-null  float64
 16  non-white                       69353 non-null  float64
 17  Distance_to_Nearest_Station     69353 non-null  float64
 18  Nearby_Station_Count            69353 non-null  float64
 19  Nearest_Station_Type            69353 non-null  object
 20  Transport_Accessibility_Score   69353 non-null  int64
 21  Dataset                         69353 non-null  object
 22  Brand Name                      0 non-null      float64
 23  is_data_reliable                69353 non-null  int64
 24  Total_Sale_Normalized           67699 non-null  float64
 25  is_logistics_strike             69353 non-null  int64
 26  is_delivery_crackdown           69353 non-null  int64
 27  is_payday_window                69353 non-null  int64
 28  is_NYE                          69353 non-null  int64
 29  is_NYD                          69353 non-null  int64
 30  is_Christmas                    69353 non-null  int64
 31  is_weekend                      69353 non-null  int64
 32  is_month_start                  69353 non-null  int64
 33  percent_muslim                  69353 non-null  float64
 34  is_ramadan                      69353 non-null  int64
 35  is_eid_al_fitr                  69353 non-null  int64
 36  is_eid_al_adha                  69353 non-null  int64
 37  is_Boxing_Day                   69353 non-null  int64
 38  is_covid_lockdown               69353 non-null  int64
 39  Inferred_Brand                  69353 non-null  object
 40  Days_Since_Open                 69353 non-null  int64
 41  rateable_value                  69353 non-null  float64
 42  distance_to_nearest_station_mi  69353 non-null  float64
 43  distance_to_mcdonalds_kfc_mi    69353 non-null  float64
 44  distance_to_mosque_mi           69353 non-null  float64
 45  distance_to_university_mi       69353 non-null  float64
 46  workplace_to_resident_ratio     69353 non-null  float64
 47  ethnic_diversity_index          69353 non-null  float64
dtypes: float64(22), int64(18), object(8)
memory usage: 25.4+ MB

In [5]:
df.isnull().sum()

postcode                              0
Day_of_Week                           0
Date                                  0
Branch Name                           0
Total Sale                         1654
outercode                             0
population                            0
households                            0
avg_household_income                  0
unemployment_rate                     0
working                               0
unemployed                            0
ab                                    0
c1/c2                                 0
de                                    0
white                                 0
non-white                             0
Distance_to_Nearest_Station           0
Nearby_Station_Count                  0
Nearest_Station_Type                  0
Transport_Accessibility_Score         0
Dataset                               0
Brand Name                        69353
is_data_reliable                      0
Total_Sale_Normalized              1654
is_logistics_strike                   0
is_delivery_crackdown                 0
is_payday_window                      0
is_NYE                                0
is_NYD                                0
is_Christmas                          0
is_weekend                            0
is_month_start                        0
percent_muslim                        0
is_ramadan                            0
is_eid_al_fitr                        0
is_eid_al_adha                        0
is_Boxing_Day                         0
is_covid_lockdown                     0
Inferred_Brand                        0
Days_Since_Open                       0
rateable_value                        0
distance_to_nearest_station_mi        0
distance_to_mcdonalds_kfc_mi          0
distance_to_mosque_mi                 0
distance_to_university_mi             0
workplace_to_resident_ratio           0
ethnic_diversity_index                0
dtype: int64

In [6]:
# from data_profiling import ProfileReport

# profile= ProfileReport(df)

# profile.to_file('report.html')

In [7]:
df = df.drop('Brand Name',axis=1)

In [8]:
df = df.drop_duplicates()

In [9]:
df = df.drop(columns=['Total_Sale_Normalized'])

In [10]:
df = df.dropna(subset=['Total Sale'])

In [11]:
df.head()

,postcode,Day_of_Week,Date,Branch Name,Total Sale,outercode,population,households,avg_household_income,unemployment_rate,...,is_covid_lockdown,Inferred_Brand,Days_Since_Open,rateable_value,distance_to_nearest_station_mi,distance_to_mcdonalds_kfc_mi,distance_to_mosque_mi,distance_to_university_mi,workplace_to_resident_ratio,ethnic_diversity_index
0,KA21 5DT,Saturday,2/1/2025,galos peri peri hamilton,347.53,KA21,686,548,13716.9812,0.43,...,0,Galos,0,1365.0,0.241441,2.277612,19.979787,14.023843,120.827,0.016
1,KA21 5DT,Sunday,2/2/2025,galos peri peri hamilton,119.68,KA21,686,548,13716.9812,0.43,...,0,Galos,1,1365.0,0.241441,2.277612,19.979787,14.023843,120.827,0.016
2,KA21 5DT,Monday,2/3/2025,galos peri peri hamilton,136.20,KA21,686,548,13716.9812,0.43,...,0,Galos,2,1365.0,0.241441,2.277612,19.979787,14.023843,120.827,0.016
3,KA21 5DT,Tuesday,2/4/2025,galos peri peri hamilton,92.67,KA21,686,548,13716.9812,0.43,...,0,Galos,3,1365.0,0.241441,2.277612,19.979787,14.023843,120.827,0.016
4,KA21 5DT,Wednesday,2/5/2025,galos peri peri hamilton,124.94,KA21,686,548,13716.9812,0.43,...,0,Galos,4,1365.0,0.241441,2.277612,19.979787,14.023843,120.827,0.016

In [12]:
df.isnull().sum()

postcode                          0
Day_of_Week                       0
Date                              0
Branch Name                       0
Total Sale                        0
outercode                         0
population                        0
households                        0
avg_household_income              0
unemployment_rate                 0
working                           0
unemployed                        0
ab                                0
c1/c2                             0
de                                0
white                             0
non-white                         0
Distance_to_Nearest_Station       0
Nearby_Station_Count              0
Nearest_Station_Type              0
Transport_Accessibility_Score     0
Dataset                           0
is_data_reliable                  0
is_logistics_strike               0
is_delivery_crackdown             0
is_payday_window                  0
is_NYE                            0
is_NYD                            0
is_Christmas                      0
is_weekend                        0
is_month_start                    0
percent_muslim                    0
is_ramadan                        0
is_eid_al_fitr                    0
is_eid_al_adha                    0
is_Boxing_Day                     0
is_covid_lockdown                 0
Inferred_Brand                    0
Days_Since_Open                   0
rateable_value                    0
distance_to_nearest_station_mi    0
distance_to_mcdonalds_kfc_mi      0
distance_to_mosque_mi             0
distance_to_university_mi         0
workplace_to_resident_ratio       0
ethnic_diversity_index            0
dtype: int64

In [13]:
df= df.drop(columns=['Dataset'])

In [14]:
df['Date']= pd.to_datetime(df['Date'])

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 67699 entries, 0 to 69352
Data columns (total 45 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   postcode                        67699 non-null  object
 1   Day_of_Week                     67699 non-null  object
 2   Date                            67699 non-null  datetime64[ns]
 3   Branch Name                     67699 non-null  object
 4   Total Sale                      67699 non-null  float64
 5   outercode                       67699 non-null  object
 6   population                      67699 non-null  int64
 7   households                      67699 non-null  int64
 8   avg_household_income            67699 non-null  float64
 9   unemployment_rate               67699 non-null  float64
 10  working                         67699 non-null  float64
 11  unemployed                      67699 non-null  float64
 12  ab                              67699 non-null  float64
 13  c1/c2                           67699 non-null  float64
 14  de                              67699 non-null  float64
 15  white                           67699 non-null  float64
 16  non-white                       67699 non-null  float64
 17  Distance_to_Nearest_Station     67699 non-null  float64
 18  Nearby_Station_Count            67699 non-null  float64
 19  Nearest_Station_Type            67699 non-null  object
 20  Transport_Accessibility_Score   67699 non-null  int64
 21  is_data_reliable                67699 non-null  int64
 22  is_logistics_strike             67699 non-null  int64
 23  is_delivery_crackdown           67699 non-null  int64
 24  is_payday_window                67699 non-null  int64
 25  is_NYE                          67699 non-null  int64
 26  is_NYD                          67699 non-null  int64
 27  is_Christmas                    67699 non-null  int64
 28  is_weekend                      67699 non-null  int64
 29  is_month_start                  67699 non-null  int64
 30  percent_muslim                  67699 non-null  float64
 31  is_ramadan                      67699 non-null  int64
 32  is_eid_al_fitr                  67699 non-null  int64
 33  is_eid_al_adha                  67699 non-null  int64
 34  is_Boxing_Day                   67699 non-null  int64
 35  is_covid_lockdown               67699 non-null  int64
 36  Inferred_Brand                  67699 non-null  object
 37  Days_Since_Open                 67699 non-null  int64
 38  rateable_value                  67699 non-null  float64
 39  distance_to_nearest_station_mi  67699 non-null  float64
 40  distance_to_mcdonalds_kfc_mi    67699 non-null  float64
 41  distance_to_mosque_mi           67699 non-null  float64
 42  distance_to_university_mi       67699 non-null  float64
 43  workplace_to_resident_ratio     67699 non-null  float64
 44  ethnic_diversity_index          67699 non-null  float64
dtypes: datetime64[ns](1), float64(20), int64(18), object(6)
memory usage: 23.8+ MB

In [16]:
df

,postcode,Day_of_Week,Date,Branch Name,Total Sale,outercode,population,households,avg_household_income,unemployment_rate,...,is_covid_lockdown,Inferred_Brand,Days_Since_Open,rateable_value,distance_to_nearest_station_mi,distance_to_mcdonalds_kfc_mi,distance_to_mosque_mi,distance_to_university_mi,workplace_to_resident_ratio,ethnic_diversity_index
0,KA21 5DT,Saturday,2025-02-01,galos peri peri hamilton,347.53,KA21,686,548,13716.9812,0.430,...,0,Galos,0,1365.0,0.241441,2.277612,19.979787,14.023843,120.827,0.0160
1,KA21 5DT,Sunday,2025-02-02,galos peri peri hamilton,119.68,KA21,686,548,13716.9812,0.430,...,0,Galos,1,1365.0,0.241441,2.277612,19.979787,14.023843,120.827,0.0160
2,KA21 5DT,Monday,2025-02-03,galos peri peri hamilton,136.20,KA21,686,548,13716.9812,0.430,...,0,Galos,2,1365.0,0.241441,2.277612,19.979787,14.023843,120.827,0.0160
3,KA21 5DT,Tuesday,2025-02-04,galos peri peri hamilton,92.67,KA21,686,548,13716.9812,0.430,...,0,Galos,3,1365.0,0.241441,2.277612,19.979787,14.023843,120.827,0.0160
4,KA21 5DT,Wednesday,2025-02-05,galos peri peri hamilton,124.94,KA21,686,548,13716.9812,0.430,...,0,Galos,4,1365.0,0.241441,2.277612,19.979787,14.023843,120.827,0.0160
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69348,WV1 1TQ,Thursday,2025-06-26,rio's piri piri wolverhampton,794.19,WV1,345,168,36481.0000,0.086,...,0,Rio's,832,8354.0,0.201000,0.052655,0.729161,0.172899,0.915,0.6348
69349,WV1 1TQ,Friday,2025-06-27,rio's piri piri wolverhampton,582.61,WV1,345,168,36481.0000,0.086,...,0,Rio's,833,8354.0,0.201000,0.052655,0.729161,0.172899,0.915,0.6348
69350,WV1 1TQ,Saturday,2025-06-28,rio's piri piri wolverhampton,458.56,WV1,345,168,36481.0000,0.086,...,0,Rio's,834,8354.0,0.201000,0.052655,0.729161,0.172899,0.915,0.6348
69351,WV1 1TQ,Sunday,2025-06-29,rio's piri piri wolverhampton,174.68,WV1,345,168,36481.0000,0.086,...,0,Rio's,835,8354.0,0.201000,0.052655,0.729161,0.172899,0.915,0.6348
69352,WV1 1TQ,Monday,2025-06-30,rio's piri piri wolverhampton,380.27,WV1,345,168,36481.0000,0.086,...,0,Rio's,836,8354.0,0.201000,0.052655,0.729161,0.172899,0.915,0.6348

In [17]:
df.sample(10)

,postcode,Day_of_Week,Date,Branch Name,Total Sale,outercode,population,households,avg_household_income,unemployment_rate,...,is_covid_lockdown,Inferred_Brand,Days_Since_Open,rateable_value,distance_to_nearest_station_mi,distance_to_mcdonalds_kfc_mi,distance_to_mosque_mi,distance_to_university_mi,workplace_to_resident_ratio,ethnic_diversity_index
8944,BS14 9HY,Thursday,2023-03-09,maeme's gilda parade,271.11,BS14,341,166,48277.0,0.0369,...,0,Maeme's,404,181.0,0.025,1.251432,2.189498,2.647235,0.457,0.2253
67353,DT4 8NY,Tuesday,2022-03-22,rio's piri piri weymouth,172.55,DT4,389,218,39524.0,0.0384,...,0,Rio's,445,6785.0,0.031,0.339855,0.211475,24.597410,0.594,0.1902
31522,B66 4BL,Tuesday,2023-06-13,rio's piri piri bearwood,370.81,B66,350,168,54473.0,0.0603,...,0,Rio's,643,2153.0,1.591,0.792280,1.213543,1.832360,0.376,0.6153
57588,B10 0UT,Monday,2025-06-02,rio's piri piri small heath,963.15,B10,592,162,39905.0,0.0622,...,0,Rio's,745,1870.0,0.421,0.643345,0.164160,1.507982,0.265,0.3993
66638,HA9 9JS,Thursday,2024-03-21,rio's piri piri wembley,716.92,HA9,554,173,59558.0,0.0190,...,0,Rio's,1175,2562.0,0.027,0.124029,0.572537,2.093933,0.353,0.6871
20675,UB6 8SQ,Sunday,2013-11-03,pepes piri piri greenford,1622.50,UB6,343,118,63403.0,0.0662,...,0,Pepe's,702,4334.0,0.018,1.084990,0.091919,2.123123,0.397,0.6806
16916,B31 2NS,Wednesday,2013-07-17,pepes piri piri birmingham,737.09,B31,253,113,56145.0,0.0359,...,0,Pepe's,563,2580.0,0.461,0.024154,2.531760,1.708162,0.364,0.5335
13650,UB1 3DA,Thursday,2022-04-21,maeme's southall,181.81,UB1,618,164,53974.0,0.0482,...,0,Maeme's,475,16810.0,0.025,0.036009,0.096134,2.807983,0.350,0.2719
47213,LE1 1DE,Thursday,2022-12-08,rio's piri piri leicester,1123.41,LE1,177,87,52040.0,0.0432,...,0,Rio's,352,28668.0,0.030,0.156083,0.401061,1.058119,1.414,0.6746
65859,HA9 9JS,Tuesday,2022-02-01,rio's piri piri wembley,678.55,HA9,554,173,59558.0,0.0190,...,0,Rio's,396,2562.0,0.027,0.124029,0.572537,2.093933,0.353,0.6871

In [18]:
df.corr(numeric_only=True)['Total Sale']

Total Sale                        1.000000
population                       -0.088170
households                       -0.107721
avg_household_income              0.085393
unemployment_rate                -0.003181
working                          -0.002667
unemployed                        0.002667
ab                               -0.110027
c1/c2                            -0.056504
de                                0.135736
white                            -0.168142
non-white                         0.168142
Distance_to_Nearest_Station       0.083685
Nearby_Station_Count              0.036160
Transport_Accessibility_Score    -0.076063
is_data_reliable                  0.206843
is_logistics_strike              -0.070268
is_delivery_crackdown            -0.001027
is_payday_window                  0.017820
is_NYE                            0.008550
is_NYD                           -0.010831
is_Christmas                     -0.015491
is_weekend                        0.121597
is_month_start                    0.002044
percent_muslim                    0.141513
is_ramadan                       -0.091135
is_eid_al_fitr                    0.007526
is_eid_al_adha                    0.005689
is_Boxing_Day                    -0.000536
is_covid_lockdown                -0.151190
Days_Since_Open                   0.207245
rateable_value                   -0.071578
distance_to_nearest_station_mi    0.083685
distance_to_mcdonalds_kfc_mi     -0.075115
distance_to_mosque_mi            -0.145783
distance_to_university_mi        -0.082396
workplace_to_resident_ratio      -0.028418
ethnic_diversity_index            0.284276
Name: Total Sale, dtype: float64

In [ ]:
from sklearn.ensemble import RandomForestRegressor

X = df.select_dtypes(include = np.number).drop(columns=['Total Sale'])

y = df['Total Sale']


rf= RandomForestRegressor(n_estimators=300,random_state=42,n_jobs=-1)
rf.fit(X,y)


corr_matrix = X.corr().abs()




upper = corr_matrix.where(np.triu(np.ones(corr_matrix.shape),k=1).astype(bool))



to_drop =  [column for  column in upper.columns if any (upper[column] > 0.95)]


print("Coumns to drop",to_drop)

X_reduced = X.drop(columns = to_drop)
print("Remaining Shapes",X_reduced)

Coumns to drop ['working', 'unemployed', 'non-white', 'Transport_Accessibility_Score', 'distance_to_nearest_station_mi']
Remaining Shapes        population  households  avg_household_income  unemployment_rate  \
0             686         548            13716.9812              0.430
1             686         548            13716.9812              0.430
2             686         548            13716.9812              0.430
3             686         548            13716.9812              0.430
4             686         548            13716.9812              0.430
...           ...         ...                   ...                ...
69348         345         168            36481.0000              0.086
69349         345         168            36481.0000              0.086
69350         345         168            36481.0000              0.086
69351         345         168            36481.0000              0.086
69352         345         168            36481.0000              0.086

           ab   c1/c2      de   white  Distance_to_Nearest_Station  \
0      0.1928  0.1682  0.6389  0.9840                     0.241441
1      0.1928  0.1682  0.6389  0.9840                     0.241441
2      0.1928  0.1682  0.6389  0.9840                     0.241441
3      0.1928  0.1682  0.6389  0.9840                     0.241441
4      0.1928  0.1682  0.6389  0.9840                     0.241441
...       ...     ...     ...     ...                          ...
69348  0.2701  0.2540  0.4759  0.5376                     0.201000
69349  0.2701  0.2540  0.4759  0.5376                     0.201000
69350  0.2701  0.2540  0.4759  0.5376                     0.201000
69351  0.2701  0.2540  0.4759  0.5376                     0.201000
69352  0.2701  0.2540  0.4759  0.5376                     0.201000

       Nearby_Station_Count  ...  is_eid_al_adha  is_Boxing_Day  \
0                       1.0  ...               0              0
1                       1.0  ...               0              0
2                       1.0  ...               0              0
3                       1.0  ...               0              0
4                       1.0  ...               0              0
...                     ...  ...             ...            ...
69348                  12.0  ...               0              0
69349                  12.0  ...               0              0
69350                  12.0  ...               0              0
69351                  12.0  ...               0              0
69352                  12.0  ...               0              0

       is_covid_lockdown  Days_Since_Open  rateable_value  \
0                      0                0          1365.0
1                      0                1          1365.0
2                      0                2          1365.0
3                      0                3          1365.0
4                      0                4          1365.0
...                  ...              ...             ...
69348                  0              832          8354.0
69349                  0              833          8354.0
69350                  0              834          8354.0
69351                  0              835          8354.0
69352                  0              836          8354.0

       distance_to_mcdonalds_kfc_mi  distance_to_mosque_mi  \
0                          2.277612              19.979787
1                          2.277612              19.979787
2                          2.277612              19.979787
3                          2.277612              19.979787
4                          2.277612              19.979787
...                             ...                    ...
69348                      0.052655               0.729161
69349                      0.052655               0.729161
69350                      0.052655               0.729161
69351                      0.052655               0.729161
69352                      0.052655               0.729161

       distance_to_university_mi  workplace_to_resident_ratio  \
0                      14.023843                      120.827
1                      14.023843                      120.827
2                      14.023843                      120.827
3                      14.023843                      120.827
4                      14.023843                      120.827
...                          ...                          ...
69348                   0.172899                        0.915
69349                   0.172899                        0.915
69350                   0.172899                        0.915
69351                   0.172899                        0.915
69352                   0.172899                        0.915

       ethnic_diversity_index
0                      0.0160
1                      0.0160
2                      0.0160
3                      0.0160
4                      0.0160
...                       ...
69348                  0.6348
69349                  0.6348
69350                  0.6348
69351                  0.6348
69352                  0.6348

[67699 rows x 32 columns]

,population,households,avg_household_income,unemployment_rate,working,unemployed,ab,c1/c2,de,white,...,is_Boxing_Day,is_covid_lockdown,Days_Since_Open,rateable_value,distance_to_nearest_station_mi,distance_to_mcdonalds_kfc_mi,distance_to_mosque_mi,distance_to_university_mi,workplace_to_resident_ratio,ethnic_diversity_index
population,1.000000,0.592763,0.291099,0.241120,0.228227,0.228227,0.134427,0.341283,0.332093,0.137638,...,0.001169,0.011364,0.001697,0.148239,0.099483,0.091388,0.172977,0.021510,0.088670,0.122288
households,0.592763,1.000000,0.275517,0.536668,0.520474,0.520474,0.268232,0.197872,0.126015,0.352398,...,0.000159,0.015404,0.017659,0.071972,0.118144,0.046837,0.453811,0.131638,0.214413,0.346868
avg_household_income,0.291099,0.275517,1.000000,0.405316,0.402791,0.402791,0.526701,0.036861,0.507315,0.023275,...,0.001259,0.014956,0.010046,0.093485,0.287175,0.271812,0.127059,0.202215,0.100854,0.322270
unemployment_rate,0.241120,0.536668,0.405316,1.000000,0.999682,0.999682,0.128741,0.222871,0.254532,0.065448,...,0.000024,0.007818,0.063693,0.021644,0.243914,0.400080,0.569602,0.035445,0.278250,0.300969
working,0.228227,0.520474,0.402791,0.999682,1.000000,1.000000,0.138493,0.217380,0.260154,0.054933,...,0.000024,0.008222,0.064119,0.020668,0.249234,0.404241,0.561025,0.034725,0.281160,0.292614
unemployed,0.228227,0.520474,0.402791,0.999682,1.000000,1.000000,0.138493,0.217380,0.260154,0.054933,...,0.000024,0.008222,0.064119,0.020668,0.249234,0.404241,0.561025,0.034725,0.281160,0.292614
ab,0.134427,0.268232,0.526701,0.128741,0.138493,0.138493,1.000000,0.195496,0.801010,0.551989,...,0.000120,0.025073,0.029768,0.202810,0.173828,0.319332,0.218497,0.016761,0.025748,0.213800
c1/c2,0.341283,0.197872,0.036861,0.222871,0.217380,0.217380,0.195496,1.000000,0.430506,0.041700,...,0.002486,0.045863,0.057201,0.024678,0.016922,0.025985,0.147581,0.481936,0.079448,0.039216
de,0.332093,0.126015,0.507315,0.254532,0.260154,0.260154,0.801010,0.430506,1.000000,0.482504,...,0.001627,0.051073,0.062319,0.171603,0.170308,0.278020,0.110983,0.278780,0.024803,0.220681
white,0.137638,0.352398,0.023275,0.065448,0.054933,0.054933,0.551989,0.041700,0.482504,1.000000,...,0.003281,0.016578,0.022139,0.038758,0.063658,0.148229,0.420347,0.241097,0.097327,0.400295
non-white,0.137638,0.352398,0.023275,0.065448,0.054933,0.054933,0.551989,0.041700,0.482504,1.000000,...,0.003281,0.016578,0.022139,0.038758,0.063658,0.148229,0.420347,0.241097,0.097327,0.400295
Distance_to_Nearest_Station,0.099483,0.118144,0.287175,0.243914,0.249234,0.249234,0.173828,0.016922,0.170308,0.063658,...,0.002194,0.029760,0.042422,0.205588,1.000000,0.308289,0.016914,0.052908,0.007163,0.008417
Nearby_Station_Count,0.150569,0.126494,0.449137,0.294134,0.292042,0.292042,0.147473,0.021828,0.149024,0.015004,...,0.000461,0.007442,0.050422,0.230165,0.633804,0.278393,0.248459,0.064172,0.065441,0.349779
Transport_Accessibility_Score,0.064816,0.076230,0.293583,0.269773,0.275537,0.275537,0.200877,0.022130,0.198370,0.063897,...,0.002433,0.019414,0.067519,0.196301,0.957607,0.318118,0.029389,0.058388,0.011998,0.009349
is_data_reliable,0.075257,0.003372,0.051605,0.139711,0.146523,0.146523,0.273229,0.087534,0.198038,0.062442,...,0.003443,0.017754,0.025829,0.053768,0.043439,0.137864,0.045062,0.025830,0.006159,0.006547
is_logistics_strike,0.000016,0.010631,0.009830,0.007225,0.006797,0.006797,0.021087,0.015542,0.028890,0.000334,...,0.003707,0.015731,0.119216,0.010404,0.040429,0.001511,0.015008,0.003391,0.003864,0.032281
is_delivery_crackdown,0.012113,0.006848,0.007739,0.009507,0.009892,0.009892,0.010029,0.002600,0.010813,0.016699,...,0.004620,0.019602,0.161362,0.024879,0.009720,0.007976,0.003856,0.033199,0.002955,0.003317
is_payday_window,0.000141,0.000688,0.001094,0.000911,0.000916,0.000916,0.000250,0.001492,0.001141,0.000048,...,0.092047,0.004722,0.007826,0.000755,0.001382,0.001236,0.003310,0.001128,0.004466,0.001052
is_NYE,0.001012,0.000507,0.000672,0.000629,0.000628,0.000628,0.000646,0.001045,0.000043,0.000319,...,0.002338,0.009919,0.005593,0.000472,0.001094,0.000794,0.001970,0.001563,0.002202,0.000576
is_NYD,0.000708,0.000465,0.001092,0.000807,0.000821,0.000821,0.001203,0.002644,0.002721,0.000641,...,0.002476,0.020292,0.005327,0.000589,0.000002,0.001671,0.000775,0.002157,0.002301,0.002730
is_Christmas,0.002348,0.000608,0.003839,0.001596,0.001599,0.001599,0.002485,0.004008,0.000159,0.001320,...,0.001948,0.008267,0.002494,0.003086,0.004094,0.003180,0.002486,0.006958,0.001887,0.005955
is_weekend,0.000705,0.000115,0.001063,0.000842,0.000884,0.000884,0.001957,0.000338,0.002008,0.000914,...,0.024212,0.001327,0.000532,0.000611,0.000675,0.000728,0.000392,0.001002,0.002004,0.001229
is_month_start,0.000972,0.000266,0.001627,0.000899,0.000915,0.000915,0.001306,0.001704,0.002242,0.000204,...,0.015664,0.001240,0.005938,0.000166,0.001348,0.000405,0.000075,0.000689,0.002383,0.000054
percent_muslim,0.090662,0.216390,0.234010,0.093326,0.102428,0.102428,0.469635,0.099696,0.371355,0.732552,...,0.001141,0.022675,0.004565,0.082486,0.188054,0.372042,0.324118,0.102549,0.053374,0.011539
is_ramadan,0.002845,0.003442,0.001339,0.005965,0.005981,0.005981,0.005557,0.006159,0.001354,0.003801,...,0.015102,0.038415,0.001456,0.004128,0.005142,0.001511,0.006333,0.006912,0.007029,0.000268
is_eid_al_fitr,0.001546,0.001599,0.004266,0.000135,0.000108,0.000108,0.000434,0.001597,0.000575,0.000085,...,0.004371,0.018548,0.005567,0.002018,0.006027,0.000538,0.003107,0.001421,0.001719,0.005688
is_eid_al_adha,0.000597,0.000287,0.003714,0.000210,0.000152,0.000152,0.001388,0.003423,0.000812,0.001637,...,0.004505,0.019114,0.008767,0.002647,0.008710,0.001972,0.001129,0.000583,0.004043,0.007395
is_Boxing_Day,0.001169,0.000159,0.001259,0.000024,0.000024,0.000024,0.000120,0.002486,0.001627,0.003281,...,1.000000,0.009548,0.005533,0.000522,0.002194,0.001298,0.004204,0.002788,0.002106,0.002499
is_covid_lockdown,0.011364,0.015404,0.014956,0.007818,0.008222,0.008222,0.025073,0.045863,0.051073,0.016578,...,0.009548,1.000000,0.252606,0.015093,0.029760,0.023117,0.008054,0.050112,0.007265,0.041064
Days_Since_Open,0.001697,0.017659,0.010046,0.063693,0.064119,0.064119,0.029768,0.057201,0.062319,0.022139,...,0.005533,0.252606,1.000000,0.007621,0.042422,0.020682,0.067125,0.099730,0.053620,0.013013
rateable_value,0.148239,0.071972,0.093485,0.021644,0.020668,0.020668,0.202810,0.024678,0.171603,0.038758,...,0.000522,0.015093,0.007621,1.000000,0.205588,0.346726,0.087011,0.143930,0.016617,0.040135
distance_to_nearest_station_mi,0.099483,0.118144,0.287175,0.243914,0.249234,0.249234,0.173828,0.016922,0.170308,0.063658,...,0.002194,0.029760,0.042422,0.205588,1.000000,0.308289,0.016914,0.052908,0.007163,0.008417
distance_to_mcdonalds_kfc_mi,0.091388,0.046837,0.271812,0.400080,0.404241,0.404241,0.319332,0.025985,0.278020,0.148229,...,0.001298,0.023117,0.020682,0.346726,0.308289,1.000000,0.158947,0.075114,0.035111,0.062315
distance_to_mosque_mi,0.172977,0.453811,0.127059,0.569602,0.561025,0.561025,0.218497,0.147581,0.110983,0.420347,...,0.004204,0.008054,0.067125,0.087011,0.016914,0.158947,1.000000,0.106288,0.384343,0.365610
distance_to_university_mi,0.021510,0.131638,0.202215,0.035445,0.034725,0.034725,0.016761,0.481936,0.278780,0.241097,...,0.002788,0.050112,0.099730,0.143930,0.052908,0.075114,0.106288,1.000000,0.078614,0.335275
workplace_to_resident_ratio,0.088670,0.214413,0.100854,0.278250,0.281160,0.281160,0.025748,0.079448,0.024803,0.097327,...,0.002106,0.007265,0.053620,0.016617,0.007163,0.035111,0.384343,0.078614,1.000000,0.124038
ethnic_diversity_index,0.122288,0.346868,0.322270,0.300969,0.292614,0.292614,0.213800,0.039216,0.220681,0.400295,...,0.002499,0.041064,0.013013,0.040135,0.008417,0.062315,0.365610,0.335275,0.124038,1.000000