In [2]:
import pandas as pd
import numpy as np

## Creating DataFrame

In [4]:
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}

df = pd.DataFrame(data)
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [9]:
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]

df2 = pd.DataFrame(data_list)
columns = ['Name','Age','City','Salary']

df2 = pd.DataFrame(data_list,columns=columns)
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [10]:
df['Name']

0     John
1     Anna
2    Peter
3    Linda
Name: Name, dtype: str

In [11]:
df['City']

0    New York
1       Paris
2      Berlin
3      London
Name: City, dtype: str

In [13]:
df[['Name','City','Age']]

    Name      City  Age
0   John  New York   28
1   Anna     Paris   34
2  Peter    Berlin   29
3  Linda    London   42

In [14]:
df['Designation'] = ["Doctor","Engineer","Doctor","Engineer"]

In [15]:
df

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000    Engineer
2  Peter   29    Berlin   62000      Doctor
3  Linda   42    London   85000    Engineer

In [18]:
df.drop('Designation',axis=1,inplace=True)

In [19]:
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [20]:
df.loc[0]

Name          John
Age             28
City      New York
Salary       65000
Name: 0, dtype: object

In [21]:
df.loc[[0,1]]

   Name  Age      City  Salary
0  John   28  New York   65000
1  Anna   34     Paris   70000

In [22]:
df.loc[[0,1]][['City','Salary']]

       City  Salary
0  New York   65000
1     Paris   70000

In [23]:
df.loc[[2,3]][['Name','Age']]

    Name  Age
2  Peter   29
3  Linda   42

In [24]:
df[df["Age"]>30]

    Name  Age    City  Salary
1   Anna   34   Paris   70000
3  Linda   42  London   85000

In [31]:
df[df["Age"] > 30 & (df["City"] == 'Paris')]

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [29]:

df2[(df2["Age"] > 30) & (df2["City"] == 'Paris')]

   Name  Age   City  Salary
1  Anna   34  Paris   70000