## Find Missing Data

In [1]:
import numpy as np
import pandas as pd

In [2]:
data = {
    'A': [1, 2, np.nan, 4, 5],
    'B': [1, 2, 3, 4, 5],
    'C': [1, 2, 3, np.nan, np.nan],
    'D': [1, np.nan, np.nan, np.nan, 5]
}

df = pd.DataFrame(data)
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [3]:
df.isna()

       A      B      C      D
0  False  False  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [4]:
df.isna().sum()

A    1
B    0
C    2
D    3
dtype: int64

## Removing Null Data

In [5]:
df.dropna()

     A  B    C    D
0  1.0  1  1.0  1.0

In [6]:
df.dropna(thresh=3)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
4  5.0  5  NaN  5.0

In [7]:
df.fillna(0)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  0.0
2  0.0  3  3.0  0.0
3  4.0  4  0.0  0.0
4  5.0  5  0.0  5.0

In [8]:
values = {'0':0,'1':100,'2':200,'D':400}

df.fillna(value=values)

     A  B    C      D
0  1.0  1  1.0    1.0
1  2.0  2  2.0  400.0
2  NaN  3  3.0  400.0
3  4.0  4  NaN  400.0
4  5.0  5  NaN    5.0

In [9]:
df.fillna(df.mean())

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  3.0
2  3.0  3  3.0  3.0
3  4.0  4  2.0  3.0
4  5.0  5  2.0  5.0

In [10]:
df1 = pd.DataFrame({"name": ["Alice", "Bob", "Charlie"]}, index=[1, 2, 3])

# Second DataFrame
df2 = pd.DataFrame({"score": [85, 90, 75]}, index=[2, 3, 4])

In [11]:
df1

      name
1    Alice
2      Bob
3  Charlie

In [12]:
df2

   score
2     85
3     90
4     75

In [13]:
df1

      name
1    Alice
2      Bob
3  Charlie

In [14]:
df1.join(df2,how='outer')

      name  score
1    Alice    NaN
2      Bob   85.0
3  Charlie   90.0
4      NaN   75.0

In [15]:
df1.join(df2)

      name  score
1    Alice    NaN
2      Bob   85.0
3  Charlie   90.0

In [ ]:
df.join